id: I68EBB198
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-28T13:37:07+00:00'
last_modified: '2022-06-08T11:33:24.945340+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG14821
  title: རིན་ཆེན་གཏེར་མཛོད་ཀྱི་དཀར་ཆག
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    '5904':
      image_group_id: I1KG15021
      title: ''
      total_pages: 132
      order: 1
      base_file: 5904.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
