id: P009512
initial_creation_type: ocr
created_at: 28/03/2020
last_modified_at: 2021-12-19 20:35:07.778360
source_metadata:
  id: bdr:W1KG14821
  title: རིན་ཆེན་གཏེར་མཛོད་ཀྱི་དཀར་ཆག
  author: ''
  volumes:
    7db0a5cdec7246ddb6d278eeec46d1a1:
      image_group_id: I1KG15021
      title: ''
      volume_number: 1
      total_pages: 132
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
